# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir public
    - bash -c "for f in *.js; do sed -i 's#\"./\\([^/]*.js\\)\"#\"./$CI_COMMIT_SHA.\\1\"#g' \$f; done"
    - 'ls && ls static'
    - bash -c "for f in *.js; do cp \$f \"$CI_COMMIT_SHA.\$f\"; done"
    - 'ls && ls static'
    - bash -c "cd static; for f in *; do cp \$f \"$CI_COMMIT_SHA.\$f\"; done"
    - 'ls && ls static'
    - cp -r *.js *.html static manifest.json vendor public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
